version: "3.8"

volumes:
  postgres-data:

services:
  app:
    build: .
    environment:
      SPRING_ACTUATOR_PORT: "8082"
      POSTGRES_HOSTNAME: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "expense_tracker"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    depends_on:
      - db
  db:
    image: "postgres:16.2-bullseye"
    environment:
      POSTGRES_DB: "expense_tracker"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "8482:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5