bank-notification-token: local-bank-notification-token

spring:
  datasource:
    url: jdbc:postgresql://localhost:5460/expensetracker
    username: postgres
    password: postgres
server:
  port: 8063
management:
  server:
    port: 8162
